
FROM ubuntu:latest
#I was getting weird init probs without declaring the run level
ENV RUNLEVEL 1
#copy this puppy into the install dir
COPY . /install
#chmod, chea?
RUN ["chmod", "+x", "/install/install-openldap.sh"]
#Install the stuff. This can be cleaner. I'm just a neanderthal and could only get it to work by using all these layers
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y openssh-server
RUN apt-get install -y maven
RUN apt-get install -y php php-cgi libapache2-mod-php php-common php-pear php-mbstring
RUN a2enconf php7.4-cgi
RUN service apache2 restart
#i was getting weird rc.d errors without the below line. I can't find the stack overflow to give cred where I found the solution :(
RUN printf '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d
#run our script to install and configure openLDAP
RUN DEBIAN_FRONTEND=noninteractive /install/install-openldap.sh
#install phpldapadmin
RUN apt-get install -y phpldapadmin
RUN mv /install/config.php /etc/phpldapadmin/config.php