
FROM ubuntu:latest
ENV RUNLEVEL 1
COPY . /install
RUN ["chmod", "+x", "/install/install-openldap.sh"]
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y openssh-server
RUN apt-get install -y maven
RUN apt-get install -y php php-cgi libapache2-mod-php php-common php-pear php-mbstring
RUN a2enconf php7.4-cgi
RUN service apache2 restart
RUN DEBIAN_FRONTEND=noninteractive /install/install-openldap.sh
RUN printf '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d
RUN dpkg-reconfigure -f noninteractive slapd
#CMD echo "openLDAP configured my dude! You might want to change up the config file though."
